import React, { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/AuthContext'
import { formatCurrency, formatDate } from '@/lib/utils'
import { calculatePayrollRun, calculateMonthlyPAYE } from '@/lib/payeCalculator'
import { DollarSign, Users, Download, CheckCircle, AlertCircle, Info, Printer, X } from 'lucide-react'
import { format, startOfMonth, endOfMonth } from 'date-fns'

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December']

function printPayslip(staff, period, profile) {
  const paye = calculateMonthlyPAYE(
    staff.salary_type === 'monthly' ? staff.salary :
    staff.salary_type === 'weekly' ? staff.salary * 4 : staff.salary * 22
  )
  const win = window.open('', '_blank')
  win.document.write(`
    <html><head><title>Payslip --- ${staff.name}</title>
    <style>
      body{font-family:Arial,sans-serif;padding:32px;font-size:13px;color:#111;max-width:500px;margin:auto}
      h1{font-size:20px;margin:0 0 2px}.logo{color:#0f2558;font-weight:700;font-size:18px}
      .period{color:#666;margin-bottom:20px;font-size:12px}
      .staff-box{background:#f8f9fa;border-radius:8px;padding:12px 16px;margin-bottom:20px}
      .row{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #f0f0f0}
      .row:last-child{border:none}.label{color:#555}.val{font-weight:500;font-family:monospace}
      .total-row{font-weight:700;font-size:14px;padding:10px 0;border-top:2px solid #ddd;margin-top:4px}
      .green{color:#059669}.red{color:#dc2626}.footer{margin-top:24px;text-align:center;font-size:11px;color:#999}
    </style></head><body>
    <div class="logo">${profile?.shop_name || '9jaTax'}</div>
    <div class="period">Payslip for ${period} -- Issued ${format(new Date(),'dd MMM yyyy')}</div>
    <div class="staff-box">
      <div><strong>${staff.name}</strong></div>
      <div style="color:#666;font-size:12px">${staff.role} -- ${staff.salary_type} pay</div>
      ${staff.tax_id ? `<div style="color:#666;font-size:11px;margin-top:4px">Tax ID: ${staff.tax_id}</div>` : ''}
    </div>
    <div class="row"><span class="label">Gross salary</span><span class="val">---${paye.monthlyGross.toLocaleString()}</span></div>
    <div class="row"><span class="label">PAYE deduction</span><span class="val red">----${paye.monthlyPAYE.toLocaleString()}</span></div>
    <div class="row"><span class="label">Pension (8%)</span><span class="val red">----${paye.monthlyPension.toLocaleString()}</span></div>
    <div class="row total-row"><span>Net pay</span><span class="val green">---${paye.monthlyNet.toLocaleString()}</span></div>
    <div style="margin-top:16px;font-size:11px;color:#888">
      <div>Annual taxable income: ---${paye.taxableIncome.toLocaleString()}</div>
      <div>Effective tax rate: ${paye.effectiveRate}%</div>
    </div>
    <div class="footer">Generated by 9jaTax -- PAYE based on FIRS PITA 2024</div>
    </body></html>
  `)
  win.document.close(); win.print()
}

export default function Payroll() {
  const { user, profile } = useAuth()
  const [staff, setStaff] = useState([])
  const [payrollData, setPayrollData] = useState([])
  const [runs, setRuns] = useState([])
  const [loading, setLoading] = useState(true)
  const [processing, setProcessing] = useState(false)
  const [tab, setTab] = useState('run')
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth())
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [showPAYEInfo, setShowPAYEInfo] = useState(false)

  useEffect(() => { if (user) load() }, [user])
  useEffect(() => { if (staff.length) compute() }, [staff, selectedMonth, selectedYear])

  async function load() {
    setLoading(true)
    const [staffRes, runsRes] = await Promise.all([
      supabase.from('staff').select('*').eq('user_id', user.id).eq('is_active', true).order('name'),
      supabase.from('payroll_runs').select('*, payroll(*, staff(name))').eq('user_id', user.id).order('created_at', { ascending: false }).limit(12),
    ])
    setStaff(staffRes.data || [])
    setRuns(runsRes.data || [])
    setLoading(false)
  }

  function compute() {
    const results = calculatePayrollRun(staff)
    setPayrollData(results)
  }

  async function processPayroll() {
    setProcessing(true)
    const totals = payrollData.reduce((s, p) => ({
      gross: s.gross + p.gross,
      paye: s.paye + p.paye,
      pension: s.pension + p.pension,
      net: s.net + p.net,
    }), { gross: 0, paye: 0, pension: 0, net: 0 })

    // Create payroll run
    const { data: run } = await supabase.from('payroll_runs').insert({
      user_id: user.id,
      period_month: selectedMonth + 1,
      period_year: selectedYear,
      total_gross: totals.gross,
      total_paye: totals.paye,
      total_pension: totals.pension,
      total_net: totals.net,
      status: 'processed',
    }).select().single()

    // Create individual payroll records
    if (run) {
      await supabase.from('payroll').insert(
        payrollData.map(p => ({
          user_id: user.id,
          staff_id: p.id,
          period_start: startOfMonth(new Date(selectedYear, selectedMonth)).toISOString().split('T')[0],
          period_end: endOfMonth(new Date(selectedYear, selectedMonth)).toISOString().split('T')[0],
          base_salary: p.gross,
          bonuses: 0,
          deductions: p.paye + p.pension,
          net_pay: p.net,
          status: 'paid',
          paid_at: new Date().toISOString(),
        }))
      )

      // Record as expense
      await supabase.from('expenses').insert({
        user_id: user.id,
        description: `Payroll --- ${MONTHS[selectedMonth]} ${selectedYear}`,
        category: 'salaries',
        amount: totals.net,
        date: new Date().toISOString().split('T')[0],
        notes: `Gross: ${formatCurrency(totals.gross)} -- PAYE: ${formatCurrency(totals.paye)} -- Pension: ${formatCurrency(totals.pension)}`,
      })
    }

    await load()
    setTab('history')
    setProcessing(false)
  }

  const totals = payrollData.reduce((s, p) => ({
    gross: s.gross + p.gross,
    paye: s.paye + p.paye,
    pension: s.pension + p.pension,
    net: s.net + p.net,
  }), { gross: 0, paye: 0, pension: 0, net: 0 })

  const period = `${MONTHS[selectedMonth]} ${selectedYear}`

  return (
    <div className="p-4 lg:p-6 max-w-5xl space-y-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <DollarSign size={18} className="text-green-bright" /> Payroll & PAYE
          </h2>
          <p className="text-sm text-white/40 mt-0.5">Process salaries with automatic FIRS PAYE and pension deductions</p>
        </div>
        <button onClick={() => setShowPAYEInfo(true)}
          className="text-xs flex items-center gap-1.5 px-3 py-2 rounded-xl"
          style={{ background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(255,255,255,0.6)' }}>
          <Info size={13} /> PAYE rates
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 rounded-xl w-fit" style={{ background: 'rgba(255,255,255,0.05)' }}>
        {['run', 'history'].map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-4 py-1.5 rounded-lg text-xs font-medium capitalize transition-all ${
              tab === t ? 'bg-[#008751] text-white' : 'text-white/40 hover:text-white'}`}>
            {t === 'run' ? 'Run payroll' : 'History'}
          </button>
        ))}
      </div>

      {/* RUN PAYROLL TAB */}
      {tab === 'run' && (
        <div className="space-y-4">
          {/* Period selector */}
          <div className="modal-panel white-top-border rounded-2xl p-4 flex items-center gap-4 flex-wrap">
            <p className="text-sm font-medium text-white">Pay period:</p>
            <select value={selectedMonth} onChange={e => setSelectedMonth(Number(e.target.value))} className="input-dark py-2 w-36">
              {MONTHS.map((m, i) => <option key={m} value={i}>{m}</option>)}
            </select>
            <select value={selectedYear} onChange={e => setSelectedYear(Number(e.target.value))} className="input-dark py-2 w-24">
              {[2023,2024,2025,2026].map(y => <option key={y} value={y}>{y}</option>)}
            </select>
            <p className="text-sm text-white/40 ml-auto">{staff.length} active staff</p>
          </div>

          {loading ? (
            <div className="space-y-2">{[1,2,3].map(i => <div key={i} className="h-16 rounded-xl animate-pulse" style={{ background: 'rgba(255,255,255,0.04)' }} />)}</div>
          ) : staff.length === 0 ? (
            <div className="modal-panel white-top-border rounded-2xl py-14 text-center">
              <Users size={28} className="mx-auto mb-2 text-white/15" />
              <p className="text-sm text-white/30">No active staff found</p>
              <a href="/app/staff" className="mt-3 inline-block text-sm text-green-bright hover:text-green-bright">Add staff members ---</a>
            </div>
          ) : (
            <>
              {/* Staff payroll table */}
              <div className="navy-card white-top-border rounded-2xl overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.03)' }}>
                        <th className="text-left px-4 py-3 text-xs font-medium text-white/40">Staff</th>
                        <th className="text-right px-4 py-3 text-xs font-medium text-white/40">Gross</th>
                        <th className="text-right px-4 py-3 text-xs font-medium text-white/40">PAYE</th>
                        <th className="text-right px-4 py-3 text-xs font-medium text-white/40">Pension</th>
                        <th className="text-right px-4 py-3 text-xs font-medium text-white/40">Net pay</th>
                        <th className="text-right px-4 py-3 text-xs font-medium text-white/40">Rate</th>
                        <th className="px-4 py-3 w-16" />
                      </tr>
                    </thead>
                    <tbody className="divide-y" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
                      {payrollData.map(p => (
                        <tr key={p.id} className="table-row-hover transition-colors">
                          <td className="px-4 py-3">
                            <p className="font-medium text-white text-sm">{p.name}</p>
                            <p className="text-xs text-white/40 capitalize">{p.role}</p>
                          </td>
                          <td className="px-4 py-3 text-right font-mono text-white/70 text-sm">{formatCurrency(p.gross)}</td>
                          <td className="px-4 py-3 text-right font-mono text-red-400 text-sm">-{formatCurrency(p.paye)}</td>
                          <td className="px-4 py-3 text-right font-mono text-amber-400 text-sm">-{formatCurrency(p.pension)}</td>
                          <td className="px-4 py-3 text-right font-mono font-bold text-green-bright">{formatCurrency(p.net)}</td>
                          <td className="px-4 py-3 text-right text-xs text-white/30">{p.effective_rate}%</td>
                          <td className="px-4 py-3">
                            <button onClick={() => printPayslip(p, period, profile)}
                              className="text-white/25 hover:text-green-bright transition-colors">
                              <Printer size={14} />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr style={{ borderTop: '2px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.03)' }}>
                        <td className="px-4 py-3 text-sm font-bold text-white">Totals</td>
                        <td className="px-4 py-3 text-right font-mono font-semibold text-white/70">{formatCurrency(totals.gross)}</td>
                        <td className="px-4 py-3 text-right font-mono font-semibold text-red-400">-{formatCurrency(totals.paye)}</td>
                        <td className="px-4 py-3 text-right font-mono font-semibold text-amber-400">-{formatCurrency(totals.pension)}</td>
                        <td className="px-4 py-3 text-right font-mono font-bold text-green-bright">{formatCurrency(totals.net)}</td>
                        <td colSpan={2} />
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>

              {/* PAYE remittance note */}
              <div className="flex items-start gap-2 px-4 py-3 rounded-xl"
                style={{ background: 'rgba(59,130,246,0.08)', border: '1px solid rgba(59,130,246,0.15)' }}>
                <Info size={14} className="text-blue-400 shrink-0 mt-0.5" />
                <p className="text-xs text-blue-300">
                  PAYE of <strong>{formatCurrency(totals.paye)}</strong> must be remitted to FIRS by the <strong>10th of next month</strong>.
                  Pension of <strong>{formatCurrency(totals.pension)}</strong> goes to PenCom-licensed PFAs.
                </p>
              </div>

              <button onClick={processPayroll} disabled={processing}
                className="w-full btn-primary py-3.5 text-base flex items-center justify-center gap-2 disabled:opacity-50 glow-green">
                {processing ? 'Processing...' : `Process ${period} payroll --- ${formatCurrency(totals.net)} net`}
              </button>
            </>
          )}
        </div>
      )}

      {/* HISTORY TAB */}
      {tab === 'history' && (
        <div className="navy-card white-top-border rounded-2xl overflow-hidden">
          {runs.length === 0 ? (
            <div className="py-14 text-center">
              <DollarSign size={28} className="mx-auto mb-2 text-white/15" />
              <p className="text-sm text-white/30">No payroll runs yet</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.03)' }}>
                    <th className="text-left px-5 py-3 text-xs font-medium text-white/40">Period</th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-white/40">Gross</th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-white/40">PAYE</th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-white/40">Pension</th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-white/40">Net paid</th>
                    <th className="text-left px-5 py-3 text-xs font-medium text-white/40">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
                  {runs.map(r => (
                    <tr key={r.id} className="table-row-hover transition-colors">
                      <td className="px-5 py-3 font-medium text-white">{MONTHS[r.period_month - 1]} {r.period_year}</td>
                      <td className="px-5 py-3 text-right font-mono text-white/60">{formatCurrency(r.total_gross)}</td>
                      <td className="px-5 py-3 text-right font-mono text-red-400">{formatCurrency(r.total_paye)}</td>
                      <td className="px-5 py-3 text-right font-mono text-amber-400">{formatCurrency(r.total_pension)}</td>
                      <td className="px-5 py-3 text-right font-mono font-bold text-green-bright">{formatCurrency(r.total_net)}</td>
                      <td className="px-5 py-3">
                        <span className="text-xs px-2 py-0.5 rounded-full bg-[#008751]/15 text-green-bright border border-emerald-500/20">
                          {r.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* PAYE Info modal */}
      {showPAYEInfo && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
          <div className="modal-panel rounded-2xl w-full max-w-md shadow-2xl">
            <div className="flex items-center justify-between px-6 py-4" style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
              <h2 className="font-semibold text-white">Nigerian PAYE Tax Bands 2024</h2>
              <button onClick={() => setShowPAYEInfo(false)} className="text-white/30 hover:text-white"><X size={18} /></button>
            </div>
            <div className="p-6 space-y-3">
              {[
                { band: 'First ---300,000', rate: '7%' },
                { band: 'Next ---300,000', rate: '11%' },
                { band: 'Next ---500,000', rate: '15%' },
                { band: 'Next ---500,000', rate: '19%' },
                { band: 'Next ---1,600,000', rate: '21%' },
                { band: 'Above ---3,200,000', rate: '24%' },
              ].map(b => (
                <div key={b.band} className="flex justify-between items-center py-2"
                  style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                  <span className="text-sm text-white/70">{b.band} (annual)</span>
                  <span className="text-sm font-bold text-green-bright">{b.rate}</span>
                </div>
              ))}
              <div className="rounded-xl p-3 mt-2" style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)' }}>
                <p className="text-xs text-white/50 leading-relaxed">
                  Deductions applied before tax: Consolidated Relief Allowance (---200k or 1% of gross, whichever is higher) + 20% of gross + Pension (8% of gross)
                </p>
              </div>
              <p className="text-xs text-center text-white/25">Source: FIRS Personal Income Tax Act (PITA) as amended</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
